### ISSUE TITLE
confusing naming addAllUser

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#75]
Should we change the name of the addAllUser method in UserList to just addUser?

Right now, the name seems to imply it adds multiple users at once to the database, but it actually just adds one.

**Comment by Hclover2003** [comment]
Just a note for now - we should probably refactor naming last to avoid unexpected naming troubles

**Comment by Hclover2003** [comment]
Similarly, in userGateway, where we are saving multiple users (saveUser saves a UserList with multiple users to the database), maybe we can rename it as well?

- saveUser makes it seem like we are saving one user to the database. Maybe something like saveUserList or saveUsers?

**Comment by YadingF** [comment]
Okay, I will explain carefully on the Javadoc, I think it would be hard to change the name now since many classes(not only users) that used this method might need to change the reference name too(so may cause many unpredicted problems), but thank you for letting me know, I will definitely pay more attention to the Javadoc, sorry to cause this confusion.
________________________________
发件人: Huayin Luo ***@***.***>
发送时间: 2022年11月30日 1:26
收件人: CSC207-2022F-UofT/course-project-collegecook ***@***.***>
抄送: Yading Feng ***@***.***>; Assign ***@***.***>
主题: Re: [CSC207-2022F-UofT/course-project-collegecook] confusing naming addAllUser (Issue #75)


Similarly, in userGateway, where we are saving multiple users (saveUser saves a UserList with multiple users to the database), maybe we can rename it as well?

  *   saveUser makes it seem like we are saving one user to the database. Maybe something like saveUserList or saveUsers?

―

**Comment by Hclover2003** [comment]
I agree, this doesn't affect the functionality, more of a change if we have time reformatting note Thanks!
